STRINGS = {
    "ru": {
        # app
        "app_title": "Music Tagger",
        "app_version": "v1.0",

        # top bar
        "music_folder": "Папка с музыкой:",
        "select_folder": "Открыть папку",
        "open_mp3": "Открыть файл",
        "scan_folder": "Показать файлы",
        "fix_selected": "Автоматически найти метаданные выбранного файла",
        "fix_all": "Автоматически найти метаданные всех файлов",
        "stop_processing": "Остановить",
        "clear_list": "Очистить список",
        "settings": "Настройки",
        "language": "Язык",

        # panels
        "tracks": "Список файлов",
        "track_info": "Информация о файле",
        "log": "Лог",
        "progress": "Прогресс обработки",
        "cover_preview": "Обложка",

        # fields
        "file": "Файл",
        "artist": "Артист",
        "title": "Название",
        "album": "Альбом",
        "year": "Год",
        "status": "Статус",
        "match": "Совпадение",
        "note": "Комментарий",
        "cover": "Обложка",

        # placeholders
        "folder_placeholder": "Выберите папку с mp3-файлами...",
        "log_placeholder": "Здесь будет отображаться ход работы приложения...",
        "no_cover_preview": "Нет обложки",

        # statuses
        "status_new": "Новый",
        "status_ready": "Готов к обработке",
        "status_skipped": "Пропущен",
        "status_searching": "Поиск...",
        "status_done": "Готово",
        "status_not_found": "Не найдено",
        "status_network_error": "Ошибка сети",
        "status_write_error": "Ошибка записи",
        "status_stopped": "Остановлено",

        # notes / messages
        "note_parsed_ok": "Исполнитель и название извлечены из имени файла",
        "note_parsed_fail": "Не удалось определить исполнителя и название из имени файла",
        "note_no_artist_title": "Недостаточно данных для поиска",
        "note_searching_mb": "Поиск данных в MusicBrainz",
        "note_loading_cover": "Загрузка обложки...",
        "note_not_found": "Подходящий результат в MusicBrainz не найден",
        "note_tags_written": "Теги успешно записаны",
        "note_tags_and_cover_written": "Теги и обложка успешно записаны",
        "note_tags_written_no_cover": "Теги записаны, но обложка не найдена",
        "note_stopped_by_user": "Обработка остановлена пользователем",

        # dialogs
        "warning": "Предупреждение",
        "error": "Ошибка",
        "success": "Готово",
        "done": "Готово",
        "result": "Результат",
        "no_folder": "Папка не выбрана",
        "no_selection": "Файл не выбран",
        "no_tracks": "Нет файлов",
        "folder_not_exists": "Указанная папка не существует.",
        "select_folder_first": "Сначала выберите папку с mp3-файлами.",
        "select_track_first": "Сначала выберите файл в таблице.",
        "track_list_empty": "Список файлов пуст.",
        "mp3_not_found_in_folder": "В выбранной папке не найдено mp3-файлов.",
        "cannot_open_file": "Не удалось открыть файл или выбранный файл не является MP3.",
        "file_already_added": "Файл уже добавлен",
        "track_already_in_table": "Файл уже есть в таблице:",
        "track_processed": "Файл обработан:",
        "cannot_process_track": "Не удалось обработать файл",
        "processing_already_running": "Обработка уже выполняется.",
        "processing_stopped": "Обработка остановлена.",
        "processing_finished": "Обработка завершена.",
        "single_track_done": "Обработка выбранного файла завершена.",
        "single_track_failed": "Обработка выбранного файла завершилась с ошибкой или пропуском.",

        # logs
        "log_app_started": "Приложение запущено. Откройте папку или отдельный mp3-файл и запустите обработку.",
        "log_folder_selected": "Выбрана папка:",
        "log_scanning_folder": "Сканирование папки:",
        "log_no_mp3_found": "MP3-файлы не найдены.",
        "log_scan_finished": "Сканирование завершено.",
        "log_added_file": "Добавлен файл:",
        "log_file_already_added": "Файл уже есть в списке:",
        "log_list_cleared": "Список файлов очищен.",
        "log_skip_no_artist_title": "Пропуск: нет исполнителя/названия для поиска",
        "log_processing": "Обработка:",
        "log_done": "Готово:",
        "log_error_skip": "Ошибка/пропуск:",
        "log_fix_all_finished": "Обработка всех файлов завершена.",
        "log_processing_started": "Запущена обработка файлов.",
        "log_processing_stopped": "Обработка остановлена пользователем.",
        "log_processing_progress": "Прогресс",
        "log_single_processing_started": "Запущена обработка выбранного файла:",

        # metadata table
        "meta_artist": "Исполнитель",
        "meta_title": "Название",
        "meta_album": "Альбом",
        "meta_year": "Год",
        "meta_cover": "Обложка",
        "meta_state": "Статус",

        # progress / summary
        "processed_count": "Обработано",
        "success_count": "Успешно",
        "stopped": "Остановлено",

        # settings dialog
        "settings_title": "Настройки",
        "settings_general": "Общие настройки",
        "settings_language": "Язык приложения",
        "settings_min_match": "Минимальное совпадение",
        "settings_timeout": "Таймаут сети (сек.)",
        "settings_download_covers": "Скачивать обложки",
        "settings_create_backup": "Создавать резервные копии",
        "settings_save": "Сохранить",
        "settings_cancel": "Отмена",
        "settings_saved": "Настройки сохранены.",
        
        # more
        "edit_metadata": "Редактировать метаданные выбранного файла вручную",
        "edit_metadata_title": "Редактирование метаданных",
        "save_metadata": "Сохранить в файл",
        "close": "Закрыть",
        "genre": "Жанр",
        "track_number": "Номер трека",
        "comment": "Комментарий",
        "select_cover": "Выбрать обложку",
        "remove_cover": "Удалить обложку",
        "cover_removed": "Обложка будет удалена",
        "custom_cover_selected": "Выбрана пользовательская обложка",
        "metadata_saved": "Метаданные сохранены.",
        "metadata_save_error": "Не удалось сохранить метаданные",
        "choose_cover_file": "Выберите файл обложки",
        "image_files": "Изображения (*.jpg *.jpeg *.png *.webp)",
        "field_empty": "—",
        "manual_edit_done": "Метаданные файла обновлены вручную",
        "track_properties": "Свойства файла",
        "track_properties_hint": "Технические параметры файла. Метаданные трека здесь не редактируются.",
        "full_path": "Полный путь",
        "file_size": "Размер файла",
        "duration": "Длительность",
        "bitrate": "Битрейт",
        "bitrate_mode": "Режим битрейта",
        "sample_rate": "Частота дискретизации",
        "channels": "Каналы",
        "channel_mode": "Режим каналов",
        "mpeg_info": "MPEG",
        "embedded_cover": "Встроенная обложка",
        "yes": "Да",
        "no": "Нет",
        "show_properties": "Свойства",
        "actions": "Действия",
        "hide_log": "Скрыть лог",
        "show_log": "Показать лог",

        # error
        "network_error_help": (
            "Проверьте подключение к интернету. В некоторых регионах доступ к сервисам, "
            "которые использует программа, может быть ограничен. Используйте средства "
            "обхода ограничений (например, zapret) с доменами, указанными на странице "
            "проекта Music Tagger на GitHub."
        ),
    },

    "en": {
        # app
        "app_title": "Music Tagger",
        "app_version": "v1.0",

        # top bar
        "music_folder": "Music folder:",
        "select_folder": "Open folder",
        "open_mp3": "Open file",
        "scan_folder": "Show files",
        "fix_selected": "Apply to selected file",
        "fix_all": "Apply to all files",
        "stop_processing": "Stop",
        "clear_list": "Clear list",
        "settings": "Settings",
        "language": "Language",

        # panels
        "tracks": "File list",
        "track_info": "File information",
        "metadata_status": "Metadata status",
        "log": "Log",
        "progress": "Processing progress",
        "cover_preview": "Cover",

        # fields
        "file": "File",
        "artist": "Artist",
        "title": "Title",
        "album": "Album",
        "year": "Year",
        "status": "Status",
        "match": "Match",
        "note": "Comment",
        "cover": "Cover",

        # placeholders
        "folder_placeholder": "Select a folder with mp3 files...",
        "log_placeholder": "The application log will appear here...",
        "no_cover_preview": "No cover",

        # statuses
        "status_new": "New",
        "status_ready": "Ready",
        "status_skipped": "Skipped",
        "status_searching": "Searching...",
        "status_done": "Done",
        "status_not_found": "Not found",
        "status_network_error": "Network error",
        "status_write_error": "Write error",
        "status_stopped": "Stopped",

        # notes / messages
        "note_parsed_ok": "Artist and title were extracted from the file name",
        "note_parsed_fail": "Could not determine artist and title from the file name",
        "note_no_artist_title": "Not enough data for search",
        "note_searching_mb": "Searching MusicBrainz",
        "note_loading_cover": "Downloading cover...",
        "note_not_found": "No suitable result found in MusicBrainz",
        "note_tags_written": "Tags were written successfully",
        "note_tags_and_cover_written": "Tags and cover were written successfully",
        "note_tags_written_no_cover": "Tags were written, but cover was not found",
        "note_stopped_by_user": "Processing was stopped by the user",

        # dialogs
        "warning": "Warning",
        "error": "Error",
        "success": "Done",
        "done": "Done",
        "result": "Result",
        "no_folder": "No folder selected",
        "no_selection": "No file selected",
        "no_tracks": "No files",
        "folder_not_exists": "The selected folder does not exist.",
        "select_folder_first": "Select a folder with mp3 files first.",
        "select_track_first": "Select a file in the table first.",
        "track_list_empty": "The file list is empty.",
        "mp3_not_found_in_folder": "No mp3 files were found in the selected folder.",
        "cannot_open_file": "Could not open the file or the selected file is not an MP3.",
        "file_already_added": "File already added",
        "track_already_in_table": "The file is already in the table:",
        "track_processed": "File processed:",
        "cannot_process_track": "Could not process the file",
        "processing_already_running": "Processing is already running.",
        "processing_stopped": "Processing stopped.",
        "processing_finished": "Processing finished.",
        "single_track_done": "Selected file processing is complete.",
        "single_track_failed": "Selected file processing finished with an error or skip.",

        # logs
        "log_app_started": "Application started. Open a folder or a single mp3 file and run processing.",
        "log_folder_selected": "Folder selected:",
        "log_scanning_folder": "Scanning folder:",
        "log_no_mp3_found": "No MP3 files found.",
        "log_scan_finished": "Scan finished.",
        "log_added_file": "Added file:",
        "log_file_already_added": "File already exists in the list:",
        "log_list_cleared": "File list was cleared.",
        "log_skip_no_artist_title": "Skipped: no artist/title available for search",
        "log_processing": "Processing:",
        "log_done": "Done:",
        "log_error_skip": "Error/skip:",
        "log_fix_all_finished": "All files have been processed.",
        "log_processing_started": "File processing started.",
        "log_processing_stopped": "Processing was stopped by the user.",
        "log_processing_progress": "Progress",
        "log_single_processing_started": "Started processing selected file:",

        # metadata table
        "meta_artist": "Artist",
        "meta_title": "Title",
        "meta_album": "Album",
        "meta_year": "Year",
        "meta_cover": "Cover",
        "meta_state": "Status",

        # progress / summary
        "processed_count": "Processed",
        "success_count": "Successful",
        "stopped": "Stopped",

        # settings dialog
        "settings_title": "Settings",
        "settings_general": "General settings",
        "settings_language": "Application language",
        "settings_min_match": "Minimum match",
        "settings_timeout": "Network timeout (sec.)",
        "settings_download_covers": "Download covers",
        "settings_create_backup": "Create backups",
        "settings_save": "Save",
        "settings_cancel": "Cancel",
        "settings_saved": "Settings saved.",

        #more
        "edit_metadata": "Edit metadata",
        "edit_metadata_title": "Metadata editor",
        "save_metadata": "Save to file",
        "close": "Close",
        "genre": "Genre",
        "track_number": "Track number",
        "comment": "Comment",
        "select_cover": "Select cover",
        "remove_cover": "Remove cover",
        "cover_removed": "Cover will be removed",
        "custom_cover_selected": "Custom cover selected",
        "metadata_saved": "Metadata saved.",
        "metadata_save_error": "Could not save metadata",
        "choose_cover_file": "Choose cover file",
        "image_files": "Images (*.jpg *.jpeg *.png *.webp)",
        "field_empty": "—",
        "manual_edit_done": "Track metadata updated manually",
        "track_properties": "Track properties",
        "track_properties_hint": "Technical audio file properties. Track metadata is not edited here.",
        "full_path": "Full path",
        "file_size": "File size",
        "duration": "Duration",
        "bitrate": "Bitrate",
        "bitrate_mode": "Bitrate mode",
        "sample_rate": "Sample rate",
        "channels": "Channels",
        "channel_mode": "Channel mode",
        "mpeg_info": "MPEG",
        "embedded_cover": "Embedded cover",
        "yes": "Yes",
        "no": "No",
        "actions": "Actions",
        "hide_log": "Hide log",
        "show_log": "Show log",
        "show_properties": "Properties",
        "network_error_help": (
            "Check your internet connection. In some regions, access to the services used "
            "by the application may be restricted. Use bypass tools (for example, zapret) "
            "with the domains listed on the Music Tagger GitHub project page."
        ),
    }
}